# Generated by Django 4.0.6 on 2022-10-11 07:18

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(db_column='customer_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('mobile_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 48, 55, 771121))),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'customer_profile',
                'ordering': ['id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'address_type',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='product_id', primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('dis_price', models.FloatField(blank=True, null=True)),
                ('available_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.category')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('vendor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('org_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 48, 55, 792123))),
            ],
            options={
                'db_table': 'vendor_profile',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 48, 55, 793117))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.CreateModel(
            name='Search_bar_history',
            fields=[
                ('id', models.AutoField(db_column='search_id', primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 48, 55, 794121))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.product')),
            ],
            options={
                'db_table': 'search_bar_history',
            },
        ),
        migrations.CreateModel(
            name='ProductSaleDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('price', models.FloatField(blank=True, max_length=30, null=True)),
                ('discount_price', models.FloatField(blank=True, max_length=30, null=True)),
                ('product_availability', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.vendorprofile')),
            ],
            options={
                'db_table': 'product_sale_details',
            },
        ),
        migrations.CreateModel(
            name='ProductMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('display_size', models.CharField(blank=True, max_length=50, null=True)),
                ('processor', models.CharField(blank=True, max_length=50, null=True)),
                ('front_camera', models.CharField(blank=True, max_length=50, null=True)),
                ('rear_camera', models.CharField(blank=True, max_length=50, null=True)),
                ('colour', models.CharField(blank=True, max_length=50, null=True)),
                ('ram', models.CharField(blank=True, max_length=20, null=True)),
                ('storage_rom', models.CharField(blank=True, max_length=20, null=True)),
                ('battery_capicity', models.CharField(blank=True, max_length=20, null=True)),
                ('os', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.product')),
            ],
            options={
                'db_table': 'product_mobile',
            },
        ),
        migrations.CreateModel(
            name='ProductLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('series', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=50, null=True)),
                ('colour', models.CharField(blank=True, max_length=50, null=True)),
                ('hard_disk', models.CharField(blank=True, max_length=30, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=80, null=True)),
                ('ram', models.CharField(blank=True, max_length=30, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('graphics_processor', models.CharField(blank=True, max_length=50, null=True)),
                ('graphics_card_description', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_speed', models.CharField(blank=True, max_length=30, null=True)),
                ('weight', models.CharField(blank=True, max_length=30, null=True)),
                ('release_date', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'db_table': 'product_laptop',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.vendorprofile'),
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 48, 55, 784116))),
                ('email', models.ForeignKey(blank=True, db_column='email', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('mobile_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, db_column='house_no/plot_no', max_length=30, null=True)),
                ('near_by', models.CharField(blank=True, max_length=30, null=True)),
                ('street_no', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, db_column='type', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.addresstype')),
            ],
            options={
                'db_table': 'customer_address',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(db_column='cart_id', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('cart_value', models.FloatField(blank=True, db_column='total_cart_value', default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 48, 55, 781125))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
