# Generated by Django 4.0.6 on 2022-11-22 10:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 5, 22, 201094)),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 5, 22, 195136)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 5, 22, 194133)),
        ),
        migrations.AlterField(
            model_name='productlaptop',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 5, 22, 199091)),
        ),
        migrations.AlterField(
            model_name='search_history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 5, 22, 206093)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 5, 22, 187087)),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role_id',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='store.role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 5, 22, 205087)),
        ),
    ]
