# Generated by Django 4.0.6 on 2022-09-26 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 10, 49, 1, 550683)),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='mobile_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 10, 49, 1, 560686)),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 10, 49, 1, 567683)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 10, 49, 1, 568683)),
        ),
    ]
