# Generated by Django 4.0.6 on 2022-10-11 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 49, 37, 111121)),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 49, 37, 106122)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 49, 37, 113121)),
        ),
        migrations.AlterField(
            model_name='search_bar_history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 49, 37, 119118)),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 49, 37, 117121)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 12, 49, 37, 118121)),
        ),
    ]
