# Generated by Django 4.0.6 on 2022-09-16 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 16, 59, 5, 559365)),
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 16, 59, 5, 563369)),
        ),
    ]
