# Generated by Django 4.0.6 on 2022-11-16 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 16, 36, 59, 512804)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 16, 36, 59, 508859)),
        ),
        migrations.AlterField(
            model_name='productlaptop',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 16, 36, 59, 511808)),
        ),
        migrations.AlterField(
            model_name='search_bar_history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 16, 36, 59, 515857)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 16, 36, 59, 502807)),
        ),
        migrations.AlterField(
            model_name='vendororgprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 16, 36, 59, 509857)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 16, 36, 59, 514860)),
        ),
    ]
