# Generated by Django 4.0.6 on 2022-09-26 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customerprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='productlaptop',
            old_name='graphics_coprocessor',
            new_name='graphics_processor',
        ),
        migrations.RenameField(
            model_name='productlaptop',
            old_name='hard_disk_size',
            new_name='hard_disk',
        ),
        migrations.RenameField(
            model_name='productlaptop',
            old_name='operating_syatem',
            new_name='operating_system',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 12, 54, 28, 775782)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 12, 54, 28, 785780)),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productlaptop',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productmobile',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 12, 54, 28, 790786)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 12, 54, 28, 791782)),
        ),
    ]
