# Generated by Django 4.0.6 on 2022-10-26 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='review_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 6, 36, 257867)),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 6, 36, 251858)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 6, 36, 259863)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='id',
            field=models.AutoField(db_column='review_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='search_bar_history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 6, 36, 265863)),
        ),
        migrations.AlterField(
            model_name='vendororgprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 6, 36, 263862)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 6, 36, 264862)),
        ),
    ]
