# Generated by Django 4.0.6 on 2022-09-27 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_brand_name_product_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmobile',
            old_name='product_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='productlaptop',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 36, 3, 133472)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 36, 3, 144473)),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 36, 3, 150471)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 36, 3, 151474)),
        ),
    ]
