# Generated by Django 4.0.6 on 2022-10-26 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_review_id_reviews_id_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 15, 5, 61402)),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 15, 5, 55398)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 15, 5, 62401)),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='search_bar_history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 15, 5, 68402)),
        ),
        migrations.AlterField(
            model_name='vendororgprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 15, 5, 66402)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 15, 5, 67402)),
        ),
    ]
