# Generated by Django 4.0.6 on 2022-09-20 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_user_profile_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 14, 58, 39, 699124)),
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 14, 58, 39, 703131)),
        ),
    ]
