# Generated by Django 4.0.6 on 2022-11-22 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cart_created_at_alter_orgprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 38, 55, 915022)),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 38, 55, 911022)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 38, 55, 909029)),
        ),
        migrations.AlterField(
            model_name='productlaptop',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 38, 55, 913020)),
        ),
        migrations.AlterField(
            model_name='search_history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 38, 55, 920022)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 38, 55, 897016)),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role_id',
            field=models.IntegerField(db_column='role_id'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user_id',
            field=models.IntegerField(db_column='user_id'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 16, 38, 55, 918021)),
        ),
    ]
