# Generated by Django 4.0.6 on 2022-10-26 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 15, 32, 931397)),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 15, 32, 922398)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 15, 32, 934404)),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search_bar_history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 15, 32, 945399)),
        ),
        migrations.AlterField(
            model_name='vendororgprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 15, 32, 941398)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 14, 15, 32, 943402)),
        ),
    ]
