# Generated by Django 4.0.6 on 2022-11-24 05:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cart_created_at_alter_orgprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='org_id',
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 11, 27, 22, 754991)),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 11, 27, 22, 754991)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 11, 27, 22, 754991)),
        ),
        migrations.AlterField(
            model_name='productlaptop',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 11, 27, 22, 754991)),
        ),
        migrations.AlterField(
            model_name='search_history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 11, 27, 22, 754991)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 11, 27, 22, 739388)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 11, 27, 22, 754991)),
        ),
    ]
