# Generated by Django 4.0.6 on 2022-10-11 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_customer_id_search_bar_history_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search_bar_history',
            old_name='productid',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 15, 34, 39, 464608)),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 15, 34, 39, 458555)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 15, 34, 39, 465555)),
        ),
        migrations.AlterField(
            model_name='search_bar_history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 15, 34, 39, 471552)),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 15, 34, 39, 469552)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 15, 34, 39, 470553)),
        ),
    ]
