# Generated by Django 4.0.6 on 2022-09-20 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_description_product_price_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 14, 59, 3, 65126)),
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 14, 59, 3, 69130)),
        ),
    ]
