# Generated by Django 4.0.6 on 2022-10-11 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_bar_history',
            name='product',
        ),
        migrations.AddField(
            model_name='search_bar_history',
            name='category_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='search_bar_history',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='search_bar_history',
            name='product_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 16, 7, 32, 833163)),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 16, 7, 32, 826157)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 16, 7, 32, 835161)),
        ),
        migrations.AlterField(
            model_name='search_bar_history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 16, 7, 32, 841161)),
        ),
        migrations.AlterField(
            model_name='search_bar_history',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 16, 7, 32, 839161)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 16, 7, 32, 840161)),
        ),
    ]
