# Generated by Django 4.0.6 on 2022-10-27 07:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_productlaptop_name_remove_productmobile_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnoxAuthtoken',
            fields=[
                ('digest', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('token_key', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'knox_authtoken',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='vendororgprofile',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendororgprofile',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 13, 5, 40, 31313)),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 13, 5, 40, 21310)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 13, 5, 40, 27312)),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.vendororgprofile'),
        ),
        migrations.AlterField(
            model_name='search_bar_history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 13, 5, 40, 34310)),
        ),
        migrations.AlterField(
            model_name='vendororgprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 13, 5, 40, 28313)),
        ),
        migrations.AlterField(
            model_name='vendororgprofile',
            name='id',
            field=models.AutoField(db_column='vendor_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 13, 5, 40, 34310)),
        ),
    ]
