# Generated by Django 4.0.6 on 2022-10-12 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_search_bar_history_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search_bar_history',
            old_name='category_name',
            new_name='search_item',
        ),
        migrations.RemoveField(
            model_name='search_bar_history',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='search_bar_history',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='search_bar_history',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='search_bar_history',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 9, 42, 428847)),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 9, 42, 422843)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 9, 42, 430840)),
        ),
        migrations.AlterField(
            model_name='search_bar_history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 9, 42, 436843)),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 9, 42, 434842)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 9, 42, 435843)),
        ),
    ]
