# Generated by Django 4.0.6 on 2022-09-29 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart_cart_value_cart_created_at_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 12, 8, 23, 358604)),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 12, 8, 23, 353606)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 12, 8, 23, 360603)),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 12, 8, 23, 364605)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 12, 8, 23, 365604)),
        ),
    ]
