# Generated by Django 4.1.4 on 2023-09-12 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_wishlist_brand_remove_wishlist_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avg_rating',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 9, 12)),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 15, 46, 23, 515067)),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 15, 46, 23, 516067)),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 15, 46, 23, 516067)),
        ),
        migrations.AlterField(
            model_name='reset_password',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 15, 46, 23, 516067)),
        ),
        migrations.AlterField(
            model_name='saveforlater',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 15, 46, 23, 519045)),
        ),
        migrations.AlterField(
            model_name='search_history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 15, 46, 23, 518047)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 15, 46, 23, 511070)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 15, 46, 23, 517067)),
        ),
    ]
