# Generated by Django 4.1.4 on 2023-08-10 09:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='shipment',
            fields=[
                ('shipment_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('order_item_id', models.PositiveIntegerField(null=True)),
                ('shipment_order_id', models.PositiveBigIntegerField(null=True)),
                ('return_shipment_id', models.PositiveBigIntegerField(null=True)),
                ('awb_code', models.CharField(default='', max_length=100)),
                ('return_awb_code', models.CharField(default='', max_length=100)),
                ('return_shipment_order_id', models.PositiveBigIntegerField(null=True)),
                ('order_amount', models.FloatField()),
                ('pickup_address', models.PositiveIntegerField()),
                ('shipping_address', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField()),
                ('alias', models.CharField(max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 23, 1, 712250))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
    ]
