# Generated by Django 4.1.4 on 2023-08-10 09:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.PositiveIntegerField(db_column='product_id')),
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection', models.CharField(choices=[('on sale', 'on sale'), ('new product', 'new product'), ('best seller', 'best seller'), ('featured product', 'featured product')], default='', max_length=20)),
            ],
            options={
                'db_table': 'collection',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(db_column='product_id')),
                ('alt', models.CharField(max_length=100, null=True)),
                ('src', models.CharField(max_length=1000, null=True)),
                ('variant_id', models.PositiveIntegerField(null=True)),
                ('path', models.ImageField(blank=True, db_column='path', null=True, upload_to='variants/images/')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='product_id', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(default='', max_length=100)),
                ('sale', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('category_id', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(default='', max_length=100)),
                ('rating', models.FloatField(blank=True, db_column='avg_rating', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('alias', models.CharField(max_length=20, null=True, unique=True)),
                ('dimensions', models.CharField(default='0.5X0.5X0.5', help_text='Please use the following format: L X B X H and values should be greater than 0.5 cm', max_length=20)),
                ('weight', models.FloatField(default=0.05, help_text='The minimum chargeable weight is 0.5 Kg')),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], default='Draft', max_length=20)),
                ('is_charged', models.BooleanField(db_column='is_charged', default=False)),
                ('shipping_charges', models.PositiveIntegerField(default=0)),
                ('other_charges', models.PositiveIntegerField(default=0)),
                ('is_wattanty', models.BooleanField(default=False)),
                ('warranty_months', models.PositiveIntegerField(default=0)),
                ('warranty_src', models.CharField(max_length=1000, null=True)),
                ('warranty_path', models.ImageField(blank=True, null=True, upload_to='product/warranty/')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 23, 1, 669252))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.PositiveIntegerField(db_column='product_id')),
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='variants',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField(db_column='product_id')),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('gst', models.PositiveIntegerField(default=18)),
                ('selling_price', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(blank=True)),
                ('quantity', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sku', models.CharField(max_length=1000, null=True)),
                ('color', models.CharField(default='', max_length=100)),
                ('image_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'variants',
            },
        ),
        migrations.CreateModel(
            name='ProductMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(blank=True, max_length=200, null=True)),
                ('model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('storage_spec', models.TextField(blank=True, db_column='storage_specifications', null=True)),
                ('battery_spec', models.TextField(blank=True, db_column='battery_specifications', null=True)),
                ('device_spec', models.TextField(blank=True, db_column='device_specifications', null=True)),
                ('camera_spec', models.TextField(blank=True, db_column='camera_specifications', null=True)),
                ('other_spec', models.TextField(blank=True, db_column='other_specifications', null=True)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='super_admin.product')),
            ],
            options={
                'db_table': 'product_mobile',
            },
        ),
        migrations.CreateModel(
            name='ProductLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, db_column='brand_name', max_length=255, null=True)),
                ('series', models.CharField(blank=True, max_length=255, null=True)),
                ('device_spec', models.TextField(blank=True, db_column='device_specifications', null=True)),
                ('display_spec', models.TextField(blank=True, db_column='display_specifications', null=True)),
                ('storage_spec', models.TextField(blank=True, db_column='storage_specifications', null=True)),
                ('other_spec', models.TextField(blank=True, db_column='other_specifications', null=True)),
                ('release_date', models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 23, 1, 674272))),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='super_admin.product')),
            ],
            options={
                'db_table': 'product_laptop',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('org_name', models.CharField(db_column='company_name', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('mobile', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('tax_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, db_column='company_description', null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 23, 1, 668252))),
                ('tax_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_profile',
                'ordering': ['id'],
            },
        ),
    ]
