# Generated by Django 4.1.4 on 2023-09-12 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0005_alter_companyprofile_date_joined_alter_images_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='variant_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='variant_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 10, 56, 51, 768765)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 10, 56, 51, 770762)),
        ),
        migrations.AlterField(
            model_name='productlaptop',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 10, 56, 51, 773760)),
        ),
    ]
