# Generated by Django 4.1.4 on 2023-08-10 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('user', models.IntegerField(db_column='user_id')),
                ('order_price', models.FloatField()),
                ('billing', models.PositiveIntegerField(blank=True, db_column='billing_address', null=True)),
                ('delivery', models.PositiveIntegerField(blank=True, db_column='delivery_address', null=True)),
                ('payment_type', models.CharField(db_column='type_of_payment', default='', max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 23, 1, 690262))),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItemHistory',
            fields=[
                ('id', models.AutoField(db_column='order_item_id', primary_key=True, serialize=False)),
                ('order', models.IntegerField(db_column='order_id')),
                ('user', models.IntegerField(db_column='user_id')),
                ('product', models.IntegerField(db_column='product_id')),
                ('alias', models.CharField(default='', max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('order_status', models.CharField(default='', max_length=50)),
                ('item_price', models.FloatField()),
                ('shipment_charge', models.FloatField(db_column='shipment_charge', default=0)),
                ('shipment_status', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 23, 1, 691261))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateTimeField(default=datetime.datetime(2023, 8, 15, 15, 23, 1, 691261))),
            ],
            options={
                'db_table': 'order_item_history',
            },
        ),
        migrations.CreateModel(
            name='viewhistory',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('product', models.PositiveIntegerField(db_column='product_id')),
                ('user', models.PositiveIntegerField(db_column='user_id')),
                ('quantity', models.PositiveIntegerField(db_column='quantity')),
                ('totalvalue', models.FloatField(blank=True, db_column='total_value', null=True)),
                ('price', models.FloatField(blank=True, db_column='price', null=True)),
                ('address', models.PositiveIntegerField(blank=True, db_column='address_id', null=True)),
                ('is_delivered', models.BooleanField(default='False')),
            ],
            options={
                'db_table': 'pre_checkout_history',
            },
        ),
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_price', models.FloatField()),
                ('payment_type', models.CharField(default='', max_length=100)),
                ('reason_for_return', models.TextField()),
                ('return_date', models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 23, 1, 707252))),
                ('order_item', models.ForeignKey(db_column='order_item_id', on_delete=django.db.models.deletion.CASCADE, to='order.orderitemhistory')),
            ],
            options={
                'db_table': 'order_return',
            },
        ),
        migrations.CreateModel(
            name='OrderItemRefund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refund', models.CharField(blank=True, db_column='stripe_refund_id', max_length=100, null=True)),
                ('status', models.CharField(db_column='refund_status', default='', max_length=100)),
                ('transaction_id', models.CharField(blank=True, db_column='stripe_transaction_id', max_length=100, null=True)),
                ('refund_amount', models.FloatField()),
                ('currency', models.CharField(blank=True, db_column='currency_type', max_length=100, null=True)),
                ('recieptno', models.CharField(blank=True, db_column='stripe_reciept_no', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 23, 1, 708252))),
                ('alias', models.CharField(max_length=20, null=True, unique=True)),
                ('orderitemid', models.ForeignKey(blank=True, db_column='order_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orderitemhistory')),
            ],
            options={
                'db_table': 'order_refund',
            },
        ),
        migrations.CreateModel(
            name='OrderDeliverySuccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_price', models.FloatField()),
                ('delivered_date', models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 23, 1, 691261))),
                ('order_item', models.ForeignKey(db_column='order_item_id', on_delete=django.db.models.deletion.CASCADE, to='order.orderitemhistory')),
            ],
            options={
                'db_table': 'order_delivery_success',
            },
        ),
        migrations.CreateModel(
            name='OrderCancelled',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_price', models.FloatField()),
                ('payment_type', models.CharField(default='', max_length=100)),
                ('reason_for_cancel', models.TextField()),
                ('cancel_date', models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 23, 1, 692261))),
                ('order_item', models.ForeignKey(db_column='order_item_id', on_delete=django.db.models.deletion.CASCADE, to='order.orderitemhistory')),
            ],
            options={
                'db_table': 'order_cancelled',
            },
        ),
    ]
