# Generated by Django 4.1.4 on 2023-09-12 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemhistory',
            name='variant',
            field=models.IntegerField(db_column='variant_id', null=True),
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='variant',
            field=models.PositiveIntegerField(db_column='variant_id', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 10, 36, 9, 18893)),
        ),
        migrations.AlterField(
            model_name='ordercancelled',
            name='cancel_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 10, 36, 9, 23890)),
        ),
        migrations.AlterField(
            model_name='orderdeliverysuccess',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 10, 36, 9, 22891)),
        ),
        migrations.AlterField(
            model_name='orderitemhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 10, 36, 9, 19893)),
        ),
        migrations.AlterField(
            model_name='orderitemhistory',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 10, 36, 9, 19893)),
        ),
        migrations.AlterField(
            model_name='orderitemrefund',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 10, 36, 9, 40880)),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 10, 36, 9, 23890)),
        ),
    ]
